web:
  build: .
  ports:
    - "127.0.0.1:8085:80"
  volumes:
    - ./conf:/opt/zendto/config
  links:
    - db
db:
  image: mysql:5.5
  environment:
    - MYSQL_ROOT_PASSWORD=mysql
    - MYSQL_DATABASE=zendto
    - MYSQL_USER=zendto
    - MYSQL_PASSWORD=zendto
